name: Deploy Site

on:
  push:
    branches:
      - main  # Ajuste para o nome da sua branch principal

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js (se necessário)
      uses: actions/setup-node@v2
      with:
        node-version: '16'  # Ajuste para a versão que você precisa

    - name: Install dependencies
      run: |
        npm install  # Ajuste se você estiver usando outra tecnologia

    - name: Build the site
      run: |
        npm run build  # Ajuste conforme necessário

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Deploy to server
      env:
        DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}  # Use secrets para credenciais
      run: |
        # Exemplo usando rsync para copiar arquivos
        rsync -avz --delete ./dist/ user@yourserver.com:/path/to/deploy

